all:
	pandoc -s topico9.md -o topico9.tex -V geometry:margin=1in -V colorlinks -V papersize:a4 -V documentclass=article --template=/home/juliano/.pandoc/default.latex
	pdflatex topico9.tex
	rm *.out *.log
